FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install streamlit requests

COPY frontend ./frontend
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]